# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TravellWonder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravellWonder
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SwiftyJSON'
  target 'TravellWonderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravellWonderUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
